spring:
  application:
    name: server
server:
  port: 8040
eureka:
  server:
    # 关闭自我保护机制 开发的时候可以开启 保证不可用的服务能够及时从列表中剔除
    enable-self-preservation: false
  instance:
    hostname: server-8040
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8020/eureka/,http://localhost:8030/eureka/